const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.video,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.video.Acts.SetVisible,
		C3.Plugins.video.Acts.Play,
		C3.Plugins.video.Acts.SetVolume,
		C3.Plugins.video.Cnds.HasEnded,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.OnTouchEnd
	];
};
self.C3_JsPropNameTable = [
	{十字上: 0},
	{十字右: 0},
	{S__6: 0},
	{十字左: 0},
	{十字下: 0},
	{十字決定: 0},
	{右オレンジ: 0},
	{左オレンジ: 0},
	{Touch: 0},
	{Audio: 0},
	{中央下: 0},
	{上真ん中: 0},
	{上右: 0},
	{上左: 0},
	{中央内右: 0},
	{中央内左: 0},
	{下中央: 0},
	{下下: 0},
	{下右上: 0},
	{下右真ん中: 0},
	{下右下: 0},
	{下左上: 0},
	{下左真ん中: 0},
	{下左下: 0},
	{重ね１: 0},
	{重ねアキレス: 0},
	{重ねライトニングランス: 0},
	{重ね敵機でくー: 0},
	{重ね超プラズマ: 0},
	{重ねVモード: 0},
	{重ねCCM変形アキレス: 0},
	{タッチエフェクト: 0},
	{ライトニングランス動画: 0},
	{超プラズマ動画: 0},
	{CCMstate: 0},
	{commandInput: 0},
	{soundPlaying: 0},
	{ImageLock: 0},
	{CommandInput2: 0},
	{BGMNumber: 0},
	{BGMPreviousState: 0}
];

self.InstanceType = {
	十字上: class extends self.ISpriteInstance {},
	十字右: class extends self.ISpriteInstance {},
	S__6: class extends self.ISpriteInstance {},
	十字左: class extends self.ISpriteInstance {},
	十字下: class extends self.ISpriteInstance {},
	十字決定: class extends self.ISpriteInstance {},
	右オレンジ: class extends self.ISpriteInstance {},
	左オレンジ: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	中央下: class extends self.ISpriteInstance {},
	上真ん中: class extends self.ISpriteInstance {},
	上右: class extends self.ISpriteInstance {},
	上左: class extends self.ISpriteInstance {},
	中央内右: class extends self.ISpriteInstance {},
	中央内左: class extends self.ISpriteInstance {},
	下中央: class extends self.ISpriteInstance {},
	下下: class extends self.ISpriteInstance {},
	下右上: class extends self.ISpriteInstance {},
	下右真ん中: class extends self.ISpriteInstance {},
	下右下: class extends self.ISpriteInstance {},
	下左上: class extends self.ISpriteInstance {},
	下左真ん中: class extends self.ISpriteInstance {},
	下左下: class extends self.ISpriteInstance {},
	重ね１: class extends self.ISpriteInstance {},
	重ねアキレス: class extends self.ISpriteInstance {},
	重ねライトニングランス: class extends self.ISpriteInstance {},
	重ね敵機でくー: class extends self.ISpriteInstance {},
	重ね超プラズマ: class extends self.ISpriteInstance {},
	重ねVモード: class extends self.ISpriteInstance {},
	重ねCCM変形アキレス: class extends self.ISpriteInstance {},
	タッチエフェクト: class extends self.ISpriteInstance {},
	ライトニングランス動画: class extends self.IWorldInstance {},
	超プラズマ動画: class extends self.IWorldInstance {}
}